name: "Conda xsar install"
description: "Conda xsar install"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: xsar
        python-version: ${{ matrix.python-version }}
    - name: xsar deps
      shell: bash -l {0}
      run: |
        . docs/scripts/conda_setenv
        . docs/scripts/conda_install_minimal
    - name: Install xsar
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Packages list
      shell: bash -l {0}
      run: |
        conda info
        python -V
        conda list
