name: "Conda xsar install"
description: "Conda xsar install"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: xsar
        environment-file: environment.yml
        condarc-file: condarc.yml
        python-version: ${{ matrix.python-version }}
    - name: Install xsar
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Packages list
      shell: bash -l {0}
      run: |
        conda info
        python -V
        conda list
    - name: Install xsar
      shell: bash -l {0}
      run: |
        pip install -e .
        
    
