name: "xsar test"
description: "xsar test with optional doc test"
runs:
  using: "composite"
  steps:
    - name: pytest
      shell: bash -l {0}
      run: |
        pip install pytest dill
        pytest
    - uses: dorny/paths-filter@v2
      id: changes
      if: github.event_name != 'schedule'
      with:
        filters: |
          doc:
            - 'doc/**'
            - 'doc/*/**'
    # run only if some file in 'doc' folder was changed
    - name: Notebook dependencies
      shell: bash -l {0}
      run: pip install -r requirements.txt
      if: github.event_name == 'schedule' || steps.changes.outputs.doc  == 'true'
    - name: Documentation test
      shell: bash -l {0}
      run: |
        cd docs
        make html
      if: github.event_name == 'schedule' || steps.changes.outputs.doc  == 'true'