name: Generate Xsar Documentation

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Xsar Documentation
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda and create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: xsar
      - name: Create Env
        run: conda install -c conda-forge rasterio">=1.2.6" gdal cartopy_offlinedata dask[array] jupyterlab geoviews holoviews datashader 'shapely<1.8.0' nbsphinx pandoc jq docutils
      - name: Install xsar
        run: |
          pip install -e .
          pip install -r requirements.txt
      - name: Generation
        run: |
          cd docs
          make html

#      - name: Sync files
#        uses: SamKirkland/FTP-Deploy-Action@4.2.0
#        with:
#          server: ftp.ifremer.fr
#          username: ifremerlogin
#          password: ${{ secrets.password }}

