name: Install test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '20 10 * * 0'
  release:
    types: [ published ]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  dynamic-matrix:
# from https://michaelheap.com/dynamic-matrix-generation-github-actions/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-matrix
        run: |
          echo "get matrix for event ${{ github.event_name }}"
          echo "::echo::on"
          python .github/actions/dynamic_matrix.py ${{ github.event_name }}
    outputs:
      os_matrix: ${{ steps.get-matrix.outputs.os_matrix }}
      python_version_matrix: ${{ steps.get-matrix.outputs.python_version_matrix }}

  build:
    needs: dynamic-matrix
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.dynamic-matrix.outputs.os_matrix) }}
        python-version: ${{ fromJson(needs.dynamic-matrix.outputs.python_version_matrix) }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      # cache conda from https://dev.to/epassaro/caching-anaconda-environments-in-github-actions-5hde
      # and https://github.com/conda-incubator/setup-miniconda#caching
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: xsar
          condarc-file: condarc.yml
          use-mamba: true
          use-only-tar-bz2: true

      - name: Set cache date and CONDA_PREFIX
        run: |
        echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "conda prefix ${{ env.CONDA_PREFIX }}"

      - uses: actions/cache@v2
        with:
          path: ${{ env.CONDA_PREFIX }}
          key: conda-cache-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: No conda cache available, create from scracth
        run: mamba env update -n xsar -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: List Packages
        run: |
          python -V
          conda info
          conda list

      - name: Minimal install
        run: pip install -e .

      - name: Minimal pytest
        run: |
          pip install pytest dill
          pytest

      # check if docs has changed
      - uses: dorny/paths-filter@v2
        id: changes
        if: github.event_name != 'schedule'
        with:
          filters: |
            docs:
              - 'docs/**'
          # run only if some file in 'doc' folder was changed
      - name: Complete notebook install
        if: github.event_name == 'schedule' || steps.changes.outputs.docs  == 'true'
        run: pip install -r requirements.txt

      - name: Documetation test
        if: github.event_name == 'schedule' || steps.changes.outputs.docs  == 'true'
        run: |
          cd docs
          make html

          

