name: Install test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 6 * * 0'
  release:
    types: [ published ]

jobs:
  dynamic-matrix:
# from https://michaelheap.com/dynamic-matrix-generation-github-actions/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-matrix
        run: |
          echo "get matrix for event ${{ github.event_name }}"
          echo "::echo::on"
          python .github/actions/dynamic_matrix.py ${{ github.event_name }}
    outputs:
      os_matrix: ${{ steps.get-matrix.outputs.os_matrix }}
      python_version_matrix: ${{ steps.get-matrix.outputs.python_version_matrix }}

  build:
    needs: dynamic-matrix
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.dynamic-matrix.outputs.os_matrix) }}
        python-version: ${{ fromJson(needs.dynamic-matrix.outputs.python_version_matrix) }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/xsar_install
      - uses: ./.github/actions/xsar_test
      #- name: Test install
      #  run: |
      #    pip install pytest dill
      #    pytest
      #
#
      #- uses: dorny/paths-filter@v2
      #  id: changes
      #  with:
      #    filters: |
      #      doc:
      #        - 'doc/**'
      #  # run only if some file in 'src' folder was changed
      #- name: Notebook dependencies
      #  run: pip install -r requirements.txt
      #  if: steps.changes.outputs.doc  == 'true'
      #- name: Documentation test
      #  run: |
      #    cd docs
      #    make html
      #  if: steps.changes.outputs.doc  == 'true'
          

