name: Install test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '20 10 * * 0'
  release:
    types: [ published ]

jobs:
  dynamic-matrix:
# from https://michaelheap.com/dynamic-matrix-generation-github-actions/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-matrix
        run: |
          echo "get matrix for event ${{ github.event_name }}"
          echo "::echo::on"
          python .github/actions/dynamic_matrix.py ${{ github.event_name }}
    outputs:
      os_matrix: ${{ steps.get-matrix.outputs.os_matrix }}
      python_version_matrix: ${{ steps.get-matrix.outputs.python_version_matrix }}

  build:
    needs: dynamic-matrix
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.dynamic-matrix.outputs.os_matrix) }}
        python-version: ${{ fromJson(needs.dynamic-matrix.outputs.python_version_matrix) }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: xsar
          environment-file: environment.yml
          condarc-file: condarc.yml
          python-version: ${{ matrix.python-version }}

      - name: Minimal install
        run: pip install -e .

      - name: Minimal pytest
        run: |
          pip install pytest dill
          pytest

      # check if docs has changed
      - uses: dorny/paths-filter@v2
        id: changes
        if: github.event_name != 'schedule'
        with:
          filters: |
            docs:
              - 'docs/**'
          # run only if some file in 'doc' folder was changed
      - name: Complete notebook install
        if: github.event_name == 'schedule' || steps.changes.outputs.docs  == 'true'
        run: pip install -r requirements.txt

      - name: Documetation test
        if: github.event_name == 'schedule' || steps.changes.outputs.docs  == 'true'
        run: |
          cd docs
          make html

          

