name: Install test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 6 * * 0'
  release:
    types: [ published ]

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-matrix
        run: |
          echo "get matrix for event ${{ github.event_name }}"
          python .github/build_matrix.py ${{ github.event_name }}
    outputs:
      os_matrix: ${{ steps.get-matrix.outputs.os_matrix }}
      python_version_matrix: ${{ steps.get-matrix.outputs.python_version_matrix }}

  build:
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.build-matrix.outputs.os_matrix) }}
        python-version: ${{ fromJson(needs.build-matrix.outputs.python_version_matrix) }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - name: Conda init
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: xsar
          python-version: ${{ matrix.python-version }}
      - name: Conda minimal dependencies
        run: |
          . docs/scripts/conda_setenv
          . docs/scripts/conda_install_minimal
      - name: Install xsar
        run: |
          pip install -e .
          pip install -r requirements.txt
      - name: Packages list
        run: |
          conda info
          python -V
          conda list
      - name: Test install
        run: pytest
      -name: Conda recommended dependencies
        run: . docs/scripts/conda_install_recommended
      -name: Documentation test
        run: |
          cd docs
          make html
          

