name: Install test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 6 * * 0'
  release:
    types: [ published ]

jobs:
  dynamic-actions:
# from https://michaelheap.com/dynamic-matrix-generation-github-actions/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-actions
        run: |
          echo "get actions for event ${{ github.event_name }}"
          echo "::echo::on"
          python .github/dynamic_actions.py ${{ github.event_name }}
    outputs:
      os_matrix: ${{ steps.get-actions.outputs.os_matrix }}
      python_version_matrix: ${{ steps.get-actions.outputs.python_version_matrix }}
      doc: ${{ steps.get-actions.outputs.doc }}

  build:
    needs: dynamic-actions
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.dynamic-actions.outputs.os_matrix) }}
        python-version: ${{ fromJson(needs.dynamic-actions.outputs.python_version_matrix) }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: debug
        run: |
          echo ${{ fromJson(needs.dynamic-actions.outputs.doc) }}
          echo ${{ needs.dynamic-actions.outputs.doc }}
      - name: Conda init
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: xsar
          python-version: ${{ matrix.python-version }}
      - name: Conda minimal dependencies
        run: |
          . docs/scripts/conda_setenv
          . docs/scripts/conda_install_minimal
      - name: Install xsar
        run: |
          pip install -e .
#          pip install -r requirements.txt
      - name: Packages list
        run: |
          conda info
          python -V
          conda list
      - name: Test install
        run: |
          pip install pytest dill
          pytest
      - name: Notebook dependencies
        run: pip install -r requirements.txt
        if: needs.dynamic-actions.outputs.doc  == 'true'
      - name: Documentation test
        run: |
          cd docs
          make html
        if: needs.dynamic-actions.outputs.doc  == 'true'
          

